/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spotify_annoy_AnnoyIndexImpl */

#ifndef _Included_com_spotify_annoy_AnnoyIndexImpl
#define _Included_com_spotify_annoy_AnnoyIndexImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppAddItem
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppAddItem
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppGetNearestByVector
 * Signature: ([FI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppGetNearestByVector___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppGetNearestByVector
 * Signature: ([FII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppGetNearestByVector___3FII
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppGetNearestByItem
 * Signature: ([FI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppGetNearestByItem___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppGetNearestByItem
 * Signature: ([FII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppGetNearestByItem___3FII
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppBuild
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppBuild
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppSave
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppSave
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppLoad
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppGetItemVector
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppGetItemVector
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppGetDistance
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppGetDistance
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_spotify_annoy_AnnoyIndexImpl
 * Method:    cppSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spotify_annoy_AnnoyIndexImpl_cppSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
